#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec 25 19:01:27 2021
@author: alivaliyev
"""

d = dict()

username = input()
password = input()
d[username] = password

username = input()
password = input()
d[username] = password

username = input()
password = input()
d[username] = password

user = input()
passw = d[user]

result = user[-4:] + passw[:-6:-1] + str(len(passw)**2 % 100)
print(result)
