#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 25 19:01:27 2021
@author: alivaliyev
"""

def process_transactions(transactions, lower_bound, upper_bound):
    low = []
    mid = []
    high = []

    for t in transactions:
        if t <= lower_bound:
            low.append(t)
        elif t >= upper_bound:
            high.append(t)
        else:
            mid.append(t)

    return [low, mid, high]
