#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 11 22:12:27 2021
@author: alivaliyev
"""

def find_most_freq_char(word):
    w=[]
    u=0
    maxim = 0
    a=word.split()
    for i in word:
        if i not in w:
            w.append(i)
            if word.count(i)>maxim:
                maxim=word.count(i)
                u=i
    return u
def encrypt_message (message):
    er=""
    res=""
    w=message.split()
    for i in w:
        freq=find_most_freq_char(i)
        er+="#"+i.replace(freq,"")
    e=list(er)
    for ik in range(1,len(e)):
        res+=e[ik]
    return res
